CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: "dc_train.pth" # uniform
  VAL_FILENAME: "dc_val_challenge.pth" # unbiased
TASK:
  KEY: "density_classification"
  NUM_NODES: 149
MODEL:
  GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/dc_dense/1b423_n-149_p-0.05_seed-1.edgelist"
  # GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/n149_p0.033_dc.edgelist"
  # AGGR: 'max'
  EMBED_EDGE: True
TRAIN:
  WEIGHT_DECAY: 0.001