CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: "dc_train.pth" # uniform
  VAL_FILENAME: "dc_val_challenge.pth" # unbiased
TASK:
  KEY: "density_classification"
  NUM_NODES: 149
MODEL:
  GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/er_n149"
  # AGGR: 'max'
  EMBED_EDGE: True
  DROPOUT: 0.0
  NOISE_REG: 0.1
TRAIN:
  WEIGHT_DECAY: 0.001