CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: ""
  VAL_FILENAME: ""
TASK:
  KEY: "seq_mnist"
  NUM_STEPS: -1
  AGGREGATE_INPUT: True
  AGGREGATE_OUTPUT: True
MODEL:
  HIDDEN_SIZE: 64
  GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/n10_p0.6_test.edgelist"
TRAIN:
  BATCH_SIZE: 512