CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: ""
  VAL_FILENAME: ""
TASK:
  KEY: "seq_mnist"
  NUM_STEPS: 196
  NUM_NODES: 12
  AGGREGATE_INPUT: True
  AGGREGATE_OUTPUT: True
MODEL:
  GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/er_n12/"
TRAIN:
  BATCH_SIZE: 512