CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: "sin_train.pth"
  VAL_FILENAME: "sin_val.pth"
TASK:
  NUM_NODES: 12
  NUM_STEPS: 23
  KEY: "sinusoid"
MODEL:
  GRAPH_FILE: "/nethome/jye72/projects/noised-rnn-networks/configs/graphs/er_n12/"
TRAIN:
  PATIENCE: 20