EXPERIMENT: "sin_seed"
CHECKPOINT_DIR: "/nethome/jye72/share/noised-rnn-networks/"
DATA:
  DATAPATH: "/nethome/jye72/projects/noised-rnn-networks/data"
  TRAIN_FILENAME: "sin_train.pth"
  VAL_FILENAME: "sin_val.pth"
TASK:
  KEY: "sinusoid"
MODEL:
  GRAPH_FILE: "configs/graphs/sin_seed_test/"
TRAIN:
  BATCH_SIZE: 100
  CHECKPOINT_INTERVAL: 10
  PATIENCE: 100